import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: "快速起步",
      items: [
        { type: 'autogenerated', dirName: 'guide' },
        {
          type: 'category',
          label: "使用开放平台",
          items: [{ type: 'autogenerated', dirName: 'learn-the-platform' }],
          collapsed: true
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: "开发文档",
      items: [{ type: 'autogenerated', dirName: 'api' }],
      collapsed: true
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
